### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Kishanjvaghela** [gallactic/gnet#20]
command:

npm install -g gnet

<img width="658" alt="screenshot 2018-12-27 at 3 17 43 pm" src="https://user-images.githubusercontent.com/11232063/50470231-a82c8d00-09ea-11e9-826b-98b8492a7c8b.png">

**Comment by Kishanjvaghela** [comment]
There was the problem with ssh setup of Git. If anyone using SSH and getting the same error, make sure u follow

1) https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

2) Add a config file in `~/.ssh/` folder which looks like ([source](https://stackoverflow.com/a/46454143/3758898))
```
   User git
   Hostname github.com
   IdentityFile ~/.ssh/id_rsa
   TCPKeepAlive yes
   IdentitiesOnly yes
```

If multiple ssh profile
```
Host gitlab.com
  User <username>
  HostName gitlab.com
  IdentityFile ~/.ssh/kishan

Host github.com
   User git
   Hostname github.com
   IdentityFile ~/.ssh/id_rsa
   TCPKeepAlive yes
   IdentitiesOnly yes
```
Make sure username is git. `User git`


3) https://help.github.com/articles/error-permission-denied-publickey/

4) install gnet WITHOUT sudo. 

5) If get this error `[Error: EACCES: permission denied, access '/usr/local/lib/node_modules']`
```
sudo chown -R (whoami) /usr/local/lib/node_modules
```

**Comment by ToniyaSundaram** [comment]
Thanks !
