### ISSUE TITLE
Logger is not displaying error message.

### ISSUE THREAD

**Issue by Kishanjvaghela** [gallactic/gnet#6]
When we print error obj using /lib/Logger.js it's displaying empty object

![screenshot 2018-12-06 at 4 43 14 pm](https://user-images.githubusercontent.com/11232063/49572329-8190ae80-f976-11e8-81c8-123885474af0.png)

If I print using console.log(""); then
![screenshot 2018-12-06 at 4 43 55 pm](https://user-images.githubusercontent.com/11232063/49572370-98370580-f976-11e8-9326-d69c0064aed3.png)

**Comment by pouladzade** [comment]
Solved in this pr: https://github.com/gallactic/gnet/pull/7#issue-236451907
